### ISSUE TITLE
Check text sizes and line breaks in different screen ratios

### ISSUE THREAD

**Issue by mickeyvanolst** [mickeyvanolst/PHOTOGRAPHIC-CUES#10]

**Comment by mickeyvanolst** [comment]
![image](https://user-images.githubusercontent.com/1071097/180241999-64473f28-ad41-46d4-adf2-c9fb593ddc0b.png)

**Comment by dudumaluf** [comment]
I think most of it its fixed ...Ive also recreated the letterbox clipping which was offsetting when resizing the browser..now its using pixel projection and rectangles drawing on top of the fullscreen final render..just need to improve some of the values logic there a bit so the opening up animation on loading progress its working for every screensize..
