### ISSUE TITLE
make HIGH / LOW res option at start

### ISSUE THREAD

**Issue by mickeyvanolst** [mickeyvanolst/PHOTOGRAPHIC-CUES#12]
Well need some icon to toggle the high/low res version

and a more prominent way for people to make a choice at landing. Feel free to delete my HIGH LOW buttons.

**Comment by dudumaluf** [comment]
for now Ive just positioned it next to the fullscreen icon.. not sure if this should be an icon acting as a toggle or just leave as it is and make it so the selected option is highlighted and the other one is slightly with opacity reduced or something,

**Comment by dudumaluf** [comment]
![image](https://user-images.githubusercontent.com/16579360/180363342-879f15dc-bf24-4c2a-8440-cc1fe2f2ab34.png)
something like this in the line version and low or high written instead of hd or 4k etc.. not sure yet, what do you think ?

**Comment by mickeyvanolst** [comment]
maybe we keep the HIGH/LOW text based buttons and put a gear to the left of it?
